spring:
  application:
    name: backend

  datasource:
    url: jdbc:mysql://localhost:3307/seetizendb?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: password

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create